config/routes.rb
Rails.application.routes.draw do
  resources :companies, only: [:index, :new, :create, :show]   
  root "companies#index"  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    validates :name, presence: true
    has_many :pitch_deck_images 
end

app/models/pitch_deck_image.rb
class PitchDeckImage < ApplicationRecord
    belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  include PitchDeckSplitter
  include CompaniesHelper

  def index   
    @companies = Company.all.order(created_at: :desc)
  end   
    
  def new   
    @company = Company.new   
  end 
  
  def show
    @company = Company.find(params[:id])
    @pitch_deck_images = @company.pitch_deck_images.order(:id)
    @images_path = UPLOADS_PATH
  end 
    
  def create
    created = CompaniesControllerHandler.new(company_params).handle_create
    if !created
      return redirect_to new_company_path, notice: "Invalid company"  
    end
    redirect_to companies_path, notice: "New company created!"   
  end    
    
  private

  def company_params   
    params.require(:company).permit(:name, :description, :attachment)   
  end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
    class CompaniesControllerHandler
        include PitchDeckSplitter

        EMPTY_STRING = ''

        def initialize(params)
            @company_params = params
        end

        def handle_create
            return false unless valid_params
            company_data = @company_params
            file_path = @company_params[:attachment].tempfile.path
            company_data[:attachment] = @company_params[:attachment].original_filename
            company = Company.create!(company_data)
            split_company_file(company, file_path)
        end

        private

        def valid_params
            return false unless valid_string(@company_params[:name])
            return false unless valid_string(@company_params[:description])
            return false unless valid_attachment(@company_params[:attachment])
            true
        end

        def valid_string(value)
            value.present? && value != EMPTY_STRING
        end

        def valid_attachment(value)
            value.present?
        end
    end 
end

app/views/companies/index.html.erb
<div>     
    <%= link_to("Add new company", new_company_path, id: 'add-company-link', class: 'black-button') %>
    <hr style="margin-top: 50px;" />

    <% if @companies.empty? %>   
    <div>   
        <p id="no-companies-label">There are no listed companies at the moment</p>    
    </div>   
    <% else %>
        <p class="section-title">Listed companies</p>

        <div>
            <% @companies.each do |company| %>
                <div class="company-container">
                    <p class="company-title"><%= company.name %></p>
                    <p style="margin-bottom: 30px;"><%= company.description %></p>
                    <%= link_to('Learn more', company_path(company), class: 'black-button') %>
                </div>
            <% end %> 
        </div> 
    <% end %>
</div>

app/views/companies/new.html.erb
<div class="form-container">  
    <% if !@company.errors.empty? %>   
        <div>   
            <ul>   
                <% @companys.errors.full_messages.each do |msg| %>   
                    <li><%= msg %></li>   
                <% end %>      
            </ul>         
        </div>   
    <% end %>      

    <%= form_for @company, html: { multipart: true } do |f| %>
        <div class="form-text-input-container">
            <span class="form-text-input-label">Name</span>
            <%= f.text_field :name %>
        </div>
        <div class="form-text-input-container">
            <span class="form-text-input-label">Description</span> 
            <%= f.text_area :description %>   
        </div>

        <div class="form-text-input-container">
            <span class="form-text-input-label">Attachment (PDF)</span>  
            <%= f.file_field :attachment, accept: 'application/pdf', class: 'file-field' %>
        </div>
        <br>
        <%= f.submit "Save", class: 'black-button submit-button' %>   
    <% end %>   
</div>  

app/views/companies/show.html.erb
<p class="section-title">About the company</p>
<p class="company-title"><%= @company.name %></p>
<p><%= @company.description %></p>


<div style="text-align: center;">
    <p class="section-title">About the business</p>
    <% @pitch_deck_images.each do |image| %>  
        <div class="pitch-image-container">
            <%= image_tag("uploads/#{image.filename}", class: 'pitch-image"') %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wefunder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header-container">
      <a href="/" id="wefunder-logo-container">
        <img src="https://www.shipbob.com/wp-content/uploads/2019/12/Wefunder_logo.png" id="wefunder-logo" />
      </a>
    </div>
    <div id="content-container"> 
        <div id="notice-label"><%= flash[:notice] %></div>   
      <%= yield %>
    </div>
  </body>
</html>